# Generated by Django 4.1.2 on 2022-10-29 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_like_post_alter_like_user_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commment',
            new_name='comment',
        ),
    ]
