# Generated by Django 4.1.2 on 2022-10-30 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userfollowing_userfollowing_unique followers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
